### ISSUE TITLE
trains-init with --file flag

### ISSUE THREAD

**Issue by metya** [allegroai/trains#105]
Hello! Can you just implement `trains-init  --file trains.conf`  feature. Or maybe I can do it in some way?

In my case, I already have configured `trains.conf` and just need to configured another trains (in docker for example), and I can't just copy it to `~/`. So it is will be great to have some functionality.

**Comment by bmartinn** [comment]
Hi @metya,

We've actually thought of a similar use case, which is why Trains has an environment-variable that allows you to specify your own configuration file :)

Just set the `TRAINS_CONFIG_FILE` to point to another config file (for example, before running your experiment):
`$ export TRAINS_CONFIG_FILE=/path/to/myfile.conf`

If you're running another instance of Trains inside a docker container, just make sure this environment variable is set inside the container (using `docker run -e` option) and points to a trains configuration file (probably stored in a folder mounted using the `docker run -v` option), for example:
```
$ docker run -v /opt/trains/custom_conf:/path/to -e TRAINS_CONFIG_FILE=/opt/trains/custom_conf/myfile.conf ...
```

**Comment by bmartinn** [comment]
Hi @metya ,

> Can you just implement trains-init --file trains.conf feature

The feature is on it's way :)

**Comment by metya** [comment]
That's super! Very much thanks. I'll try an env variable.
