### ISSUE TITLE
problem with submodule updates

### ISSUE THREAD

**Issue by tomeramit** [allegroai/trains#112]
Hi,
I am using a submodule inside my code, on the father repo I committed the change when moving the child repository, and when I check the venvs-builds package git status, I see that the pointer to the submodule is modified (in my repo on my local pc it is not modified, and is is commited to the git)

when I do git submodule update it fix the problem, but when I launch experiment it goes back again.

how can I solve this? what I do wrong?

**Comment by bmartinn** [comment]
Hi @tomeramit ,
1) What version of *trains-agent* are you using?
I think there was a fix in 0.13.2 that might have something to do with sub-modules
2) If you do a clean `git clone --recursive` , will you get the correct version of the submodules ?
3) If you are unsure of the specific commit ID in the main repository, you can edit the experiment and instead of specific commit, you can select the latest in the master branch

**Comment by tomeramit** [comment]
1. I'm using train-agent version 0.13.2
2. when I do "git clone -b branch_name repo_name --recursive" it's working correctly
If I do "git submodule update" on the repo inside the venvs-builds it's fixes the problem, but when I launch the experiment it goes back into the wrong submodule commit state

**Comment by bmartinn** [comment]
@tomeramit did you try option (3) ?

Are you getting the correct repository and sub-repo if you do:
```console
git clone <repo_name> --recursive
git fetch --all --recurse-submodules
git checkout <Specific commit id as seen on the experiment Execution section>
```

And if you do not, does that help?
```console
git submodule update --recursive
```

**Comment by bmartinn** [comment]
Hi @tomeramit,

Please try out the following Trains Agent fix version and let me know if it solves your issue:
`$ pip install trains-agent==0.14.0rc0`

**Comment by tomeramit** [comment]
now its working!
thanks!
