### ISSUE TITLE
Iteration number on "Debug images"

### ISSUE THREAD

**Issue by DdHms** [allegroai/trains#116]
While training I show images using matplotlib.imshow, one image per epoch yet in Trains the images are not merged together to a single image with an iteration progress but rather many images all at iteration 0.
I tried it both with and without closing the figures every iteration
BTW kudos for the new UI for debug images in version 0.14.1

Thanks in advance,
DD HMS

**Comment by JDennisJ** [comment]
Hi @DdHms ,

The debug images are sorted by iteration.

I'm trying to understand better the scenario, you have for each epoch something like:
```
plt.imshow(image)
plt.show()
```

or just the `plt.imshow(image)` for each epoch? and `plt.show()` at the end?
If you could share an example, it would be great :)

p.s.
Thanks for the UI compliments 😃

**Comment by DdHms** [comment]
I used:

plt.imshow(image)

plt.show()

Once every epoch and also tried:

Plt.close('all')

plt.imshow(image)

plt.show()

**Comment by bmartinn** [comment]
Hi @DdHms ,

Debug Images are grouped by titles, then showed by iteration number.
The idea is that if, for example, I have "failed" images with running iteration numbers and "successful" images. This makes a nice clean way to review the performance while training.

The way *trains* integrates with `matplotlib`, is that in case the plot has no "title", *trains* will automatically give it one, with a running number, this way we do not loose any plots, but the outcome of that is that they are not grouped (because how would we know how to differentiate between the "fail" examples and the "successful" ones, right?)

Specifically in your case you can just give it a title, see [example](https://github.com/allegroai/trains/blob/master/examples/matplotlib_example.py#L34):
```python
plt.imshow(m)
plt.title('successful')
plt.show()
```

You could also upload the image directly with the *trains* [Logger interface](https://github.com/allegroai/trains/blob/master/examples/manual_reporting.py#L23):
``` python
logger = Task.current_task().get_logger()
logger.report_image("fail", "image 1", iteration=1, image=m1)
logger.report_image("fail", "image 2", iteration=1, image=m2)
```

**Comment by DdHms** [comment]
Great, thanks for letting me know. I'll close the issue and write the
solution/ explain my misunderstanding.

**Comment by DdHms** [comment]
Thanks to the Trains team I understand that you can either group images by **title**:
```
plt.imshow(m)
plt.title('successful')
plt.show()
```
Or explicitly write to the Trains logger:
```
logger = Task.current_task().get_logger()
logger.report_image("fail", "image 1", iteration=1, image=m1)
logger.report_image("fail", "image 2", iteration=1, image=m2)
```
Thanks for the quick answer
