### ISSUE TITLE
How to sort the model by certain metrics?

### ISSUE THREAD

**Issue by VoVAllen** [allegroai/trains#12]
How to sort the model by certain metrics? Such as final test accuracy

**Comment by bmartinn** [comment]
Models are associated to the experiments that created them. In order to sort experiments by custom metrics, add a custom column in the experiments page, like so:
![Adding a custom column](https://github.com/bmartinn/trains/blob/dev/docs/screenshots/set_custom_column.png?raw=true)

Once the column is added, you can sort using the column header:
![Custom column header](https://github.com/bmartinn/trains/blob/dev/docs/screenshots/custom_column.png?raw=true)

**Comment by VoVAllen** [comment]
Thanks a lot! I would say it's hard to find this :)
