### ISSUE TITLE
Scalar series labels in compare adding random html after action

### ISSUE THREAD

**Issue by WillNichols726** [allegroai/trains#127]
The series labels start out ok, but the moment I do anything (zoom, hover, etc.) the random html appears. 

![image](https://user-images.githubusercontent.com/45394583/80713452-76857380-8ac1-11ea-9ad3-1534ffd91d76.png)

Trains 0.14.1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0

**Comment by WillNichols726** [comment]
Clarification, it only appears when I zoom using Ctrl+ScrollWheel

**Comment by bmartinn** [comment]
Hi @WillNichols726 
The bug is verified, I can reproduce it on Firefox and on Chrome, regardless of the host OS.

A quick fix:  once you are done with zooming the page, if you refresh the page, the legend will go back to normal.

BTW, 
I was only able to reproduce this behavior by changing the zoom of the entire page (with either ctrl+wheel or ctrl+plus/minus)
What did you mean by "the moment I do anything (zoom, hover, etc.)"?
Hover seems to work for me, and also enabling/disabling a specific series on the graph...

**Comment by WillNichols726** [comment]
@bmartinn As per my second comment, I only see the bug when doing whole page zooms.

And as always, thanks again for such an awesome ML platform!

**Comment by bmartinn** [comment]
Hi @WillNichols726,
I forgot to update here, the bug was fixed in *trains-server* v0.15 :)
