### ISSUE TITLE
Multitask pipeline: how?

### ISSUE THREAD

**Issue by H4dr1en** [allegroai/trains#130]
Hi, first of all thanks for the amazing job 👍 

## Context

I usually wrap my training scripts inside a python package (say `ml-engine`). This allows me to introduce a CLI for the package, with several endpoints, say:
- `ml-engine train [OPTIONS]`
- `ml-engine valid [OPTIONS]`
- `ml-engine infer [OPTIONS]`
- `ml-engine convert [OPTIONS]`

Typically, each command has its own dependencies requirements and I create a specific conda environment for each one of them. I can then easily install the `ml-engine` thanks to its `extra_require` property defined in its `setup.py`:

```
setup(...,
    extra_require= {"train": [torch=1.0.0], 
                              "valid": [torch=0.4.0], 
                              "infer": [onnx=1.0.0],
                              "convert": [onnx==1.1.0]})
```

I am considering moving to `trains`, but I would need to solve the following problem:

## Problem

I define one experiment by a series of ordered steps, as follows (pseudo-code):

```
#/bin/sh
conda activate train-env
ml-engine train [OPTIONS]
conda activate valid-env
ml-engine valid [OPTIONS]
conda activate convert-env
ml-engine convert [OPTIONS]
```

In `trains`, I would therefore need to have either:
- an experiment that is able to switch between different envs (logic executed inside the agent). Probably the agent is not designed to do such a thing, but I could simply create the new envs I need within the script and switch between then. However this sounds ugly.
- 3 different experiments, of the same project/name, with 3 different environments. This definitely seems to be in the scope of what is explained in the [task-pipelining](https://allegro.ai/docs/examples/examples_tasks/#task-pipelining) section of the doc. I would the need a controller Task that would schedule the `train`, `valid` and `convert` tasks one after the others, passing the parameters from one task to the next one. Is it possible? Is it a valid use-case of the task-pipelining? (Was it meant to be used this way?)

I would be glad to know your opinion on how to fit this use-case in `trains` 👍

**Comment by bmartinn** [comment]
@H4dr1en thank you for the kind words, always appreciated :smile: 
Your design looks very neat and packaging the code in `ml-engine` wheel with different installation contexts should make it a breeze to use.

I would suggest having three experiment "types", then use them as templates.
What I mean is, let's assume you "manually" (i.e. without *trains-agent*) executed the `train.py` , it creates a new experiment named "my trains template". This experiment actually holds the entire environment it was executed in (specifically the conda 'train-env').
Now let's repeat the process for the rest of the experiment types. We should end up with:
"template trains", "template validation" etc.

Now first we can obviously clone them and launch them to the "trains-agent" from the UI, editing the hyper-parameter (lets assume we have something like "input model" there) so that for example "template validation" will get input model that "template train" created.

The first question is how to we pass the information from one step to the other, I see two simple options
1. Use argparse (or connect a dict to the Task) and pass a direct link to the models file (or any other output one experiment needs to pass to the next one). FYI if you need to download and cache these files [StorageManager](https://github.com/allegroai/trains/blob/master/trains/storage/manager.py#L13) will take care of that

2. Make the code `Trains` aware and only pass 'task-id' as parameter, then code itself can get the data from the Task object (including artifacts and models). The idea here is that Trains takes care of all the downloading and caching, so your code becomes "machine agnostic" (well as long as the actual files are accessible from both machines, like automatically stored on the trains-server or s3/gs/azure or shared folder, see [output_uri](https://allegro.ai/docs/examples/examples_models/#centralized-model-storage) magic :)
you can check this [example](https://allegro.ai/docs/examples/examples_models/#continue-previous-training)

Now to the piping design. If we assume the easiest way to go about it, is three different Tasks, then we have two options for piping.
1. Experiment A can launch experiment B when it's done, directly from it's own code. In a similar way to this [example](https://github.com/allegroai/trains/blob/master/examples/automl/task_piping_example.py#L30), the code in Experiment A can clone the "template experiment B" change the parameters and push it into the execution queue.
This design makes sure that once you start the process at step 1, all the rest of the steps will be automatically executed in due time. (obviously when you abort one of the experiments in the pipline the rest of the pipeline will not be executed, which is what we want).
2. Create a controller Task, that manages all the different steps, and launch them in order. Actually in the next Trains-Server version, we are adding a specific queue for exactly these kind of things. Currently you have to run the controller experiment "manually" (i.e. on a machine you control regardless of *trains-agent*).
We are now working on making it easier to create these types of controllers directly from code, so that you can create a complicated logic of running and connecting experiments with as little as possible lines of code. If this is something that is of interest I can upload the latest interface to my fork, feedback is always appropriated.
Here is a simple code snippet to get started with controllers, let's assume we jut created "cloned_task" like in this [example](https://github.com/allegroai/trains/blob/master/examples/automl/task_piping_example.py#L30):
```python
while cloned_task.status not in ('stopped', 'completed', 'failed'):
    # check every two minutes
    sleep(120)
```


BTW:
The idea of the "services" queue is to let you easily launch controllers, without the need to run them "manually" on your machine. You can already start using "services"  queue with the latest trains-agent RC:
```bash
pip install trains-agent==0.14.2rc2
trains-agent daemon --services-mode --create-queue --queue services -d
```

BTW 2:
If you need to use your 'ml-engine' in a another Task, for example inference service, you can edit the "Installed Packages" and just add:
```
ml-engine[infer]
```
it will do what you expect :)

**Comment by bmartinn** [comment]
Hi @H4dr1en 
:balloon:  See reply [here](https://github.com/allegroai/trains/issues/138#issuecomment-637566867) , Let me know if we missed anything :wink:

**Comment by H4dr1en** [comment]
Sounds good, closing here also 👍
