### ISSUE TITLE
Getting the current task in PyTorch DistributedDataParallel

### ISSUE THREAD

**Issue by bomri** [allegroai/trains#132]
Hi,

I have a question about `Task.current_task()` method.
I am working with PyTorch and training using `DistributedDataParallel`, which uses multi-process and not single-process multi-thread.
The task is been initiated on the main process at the beginning, before the `mp.spawn`, and the processes get it by using `Task.get_task(task_id)`. However, internally the current task does not seems to be available. How can I still get the current task in this type of setup?

Thanks!

**Comment by bmartinn** [comment]
Hi @bomri 
Yes, torch distributed is fully supported (as well as other sub-process parallelization solutions)
Here is how it works, the main process (the one starting this entire flow) runs : 
`task = Task.init('examples', 'torch distributed')`
Then any sub-process can either run:
`task = Task.current_task()` or even call again the `Task.init(...)`.
The idea is that the main process passes the information to the sub-processes, that it had already initialized the Task, and what the Task.id is. This means any sub-process will just use this Task.id instead of creating a new one. As you notice the first `Task.init` should eb called before the `mp.spawn` so that all the information is passed to the sub-processes.

Make sense?

BTW:
Which OS are you using? There are a few issues with torch distributed on Windows (basically no fork...), but they are mostly torch related and not *Trains* related

**Comment by bomri** [comment]
I'm initializing the task before the spawn, but `task = Task.current_task()` always returns None. Running `Task.init()` for each process does return the same task correctly and from that point the `current_task()` works for internal functions.
But I get lot's of warnings like:
_Task connect, second input model is not supported, adding into comment section_
_trains.Task - INFO - Task connect, second input model is not supported, adding into comment section_
_Could retrieve model location, skipping auto model logging_

If I save the task_id in the main process and pass it to each process I am able to use get_task with that id and get the task properly 

I am running on ubuntu 18.04

**Comment by bmartinn** [comment]
> I'm initializing the task before the spawn, but task = Task.current_task() always returns None. 

If the sub-process is forked (the default behavior on posix OS), all the local variables are copied to the sub-process, that includes the current_task.
However Torch distributed is creating the subprocesses with [Popen](https://github.com/pytorch/pytorch/blob/master/torch/distributed/launch.py#L252), which means the current_task variable is not passed. In order for the sub-process to get it, it should basically run the same code as the main process, i.e. `Task.init` it will automatically get the correct task ID, as you noticed.

> Task connect, second input model is not supported, adding into comment section

The warning you are getting is for loading the same model weights file multiple times (I assume from the multiple instances). Basically it says that logging the input weights is currently limited to a single weights file per experiment, and the second loaded weights file will be logged in the comment section of the experiment. I think we should check that if you are loading the same object multiple time it will know not to output the message, as it already logged the model weights and its the same one :)

> If I save the task_id in the main process and pass it to each process I am able to use get_task with that id and get the task properly

`Task.get_task` will work regardless of anything else, and from any machine. But `Task.get_task` will not auto-magically collect the console outputs, TensorBoard  matplotlib etc.

**Comment by bomri** [comment]
upgrading to allegroai-3.2.0rc0 & trains-0.14.3, and using the exact same task init variables as in the main process seems to solve this issue.

Thanks @bmartinn for helping!

**Comment by bmartinn** [comment]
Awesome :)
Closing this issue, if the problem resurfaces, feel free to re-open.
