### ISSUE TITLE
experiments requirements are overriden after task execution

### ISSUE THREAD

**Issue by H4dr1en** [allegroai/trains#133]
## Context

Clone an experiment in the web interface, replace with the following requirements:

```
.[train]
```

## Problem

After executing the experiment, the installed packages list is changed in the experiment:

```
Cython  # Not explicitely specified in the requirements
# all actual packages installed
# dependencies of the local package
private-package  # This private package does not have the path to the private repo
. # no more [train] extra config filter
```

I understand that it is usefull to see the actual packages installed, but I would also like to have the first list unchanged and not overwritten, especially because in the second list one private package is listed without the link to its private repo. Therefore if I clone the experiment as such it will not be able to run it again: it will fail because pip won't find the `private-package` in PYPI).

I would suggest to store the resulting env built when running the experiment as a specific artifact of the task (visible in the web interface as a tab in results of the experiment), but leave the list of requirements specified by the user untouched, WDYT?

**Comment by bmartinn** [comment]
Hi @H4dr1en ,

>I understand that it is useful to see the actual packages installed, but I would also like to have the first list unchanged and not overwritten

Yes, there is kind-of a process we think is the safest, but there are no real restrictions.
You executed a code on your machine, it creates an experiment, with your local set of installed packages (a limited list, only containing the actual packages your code use, without dependencies)
Then you clone the experiment and send the cloned experiment for the *trains-agent* to be executed.
The *trains-agent* will update back the full installed set of packages (including dependence) so that this environment can always be reproduced.
So now you end up with, "original" experiment with small set of dependencies, and cloned experiment that will always reproduce the exact same environment for you use.

Notice that you could also only edit an experiment once it was cloned, and not on the "original" one. I guess that's our way to incentivize you to clone the original experiment :)

> . # no more [train] extra config filter

Since the *trains-agent* updates the entire environment it will contain all the packages including the [extra] packages that were originally requested. So for example trains[s3] will cause boto3 to be installed, so we end up with: trains , boto3 in the "installed packages" list.

> private-package  # This private package does not have the path to the private repo

PIP just introduced support for it, so you need to make sure you upgrade. 
In the trains.conf file, change [pip_version](https://github.com/allegroai/trains-agent/blob/master/docs/trains.conf#L45) to `pip_version: "<21",`
```
pip install 0.14.2rc2
```

> Cython  # Not explicitely specified in the requirements

We always try to install Cython, as pip will not install it for packages the require build, and too many setups will get broken if it is not there (e.g. pycocotools). Also, we could not find a downside :)


What do you think?

**Comment by H4dr1en** [comment]
Thanks for the detailed answer! 

> Since the trains-agent updates the entire environment it will contain all the packages including the [extra] packages that were originally requested. So for example trains[s3] will cause boto3 to be installed, so we end up with: trains , boto3 in the "installed packages" list.

Thanks for pointing that out!

> PIP just introduced support for it, so you need to make sure you upgrade.
In the trains.conf file, change pip_version to pip_version: "<21",

Just to be sure: you meant `pip_version: ">=20.1"`, right?

**Comment by bmartinn** [comment]
> Just to be sure: you meant pip_version: ">=20.1", right?

Well both will work, but we try to limit the pip version, as we saw that from time to time there is a slight change in the way pip behaves. The thing is, for every experiment executed, a new venv is created, and in that venv we make sure the pip version used for the installation is supported.
In your case both will work but ">=20.1" will basically always get the latest pip version, where as "<21.0" will not move to the next major update (which might act a bit differently from the current one). Bottom line, stability :)

**Comment by H4dr1en** [comment]
@bmartinn Maybe `pip_version: "<21"` should be set as the default value when user calls `trains-agent init`?

**Comment by bmartinn** [comment]
@H4dr1en actually the default is "<20" see [here](https://github.com/allegroai/trains-agent/blob/master/docs/trains.conf#L45) and actually internally [here](https://github.com/allegroai/trains-agent/blob/master/trains_agent/backend_api/config/default/agent.conf#L29)

The reason for the v20 limit, is actually bad experience we had with this specific release, so far we noticed that v19 was very stable. We are waiting to see how stable v2x+ are before changing the default, as a lot of changes were introduced in v20+

Thanks for pointing the missing documentation, I'll make sure we update it.
