### ISSUE TITLE
Experiments still running forever

### ISSUE THREAD

**Issue by databill86** [allegroai/trains#137]
Hello, first of all thank you for this amazing tool 👍

**Describe the bug**
I'm not sure if it's a bug. 

I launched the docker compose of the whole Trains ecosystem, and I tried to manage my local experiments in the dockerised trains web server. 
This is how I configured my training experiment : 
```
    from trains import Task
    task = Task.init(project_name="ml experiment", task_name="training model1")
```
Then I configured the credentials and server access on docker : 
- Web server on port 8080
- API server on port 8008
- File server on port 8081

I launched my training script, I can see the experiment in the web server. 
When my script is terminated, the experiment is still running on the web server. 

I used Spyder to run the script. 

**Desktop (please complete the following information):**
 - OS : Windows (script to train a simple ML model) 
 - Docker : Trains web server, API, File server, ... 
 - IDE : Spyder

**Comment by bmartinn** [comment]
@databill86 thank you so much for the support, really appreciate it! :)

To your issue, when the script ends, *trains* will automatically close it's experiment.
It seems that for some reason that never happened 
(notice than even when you press ctrl-c/break it should close the experiment but mark it as aborted, instead of completed)

What's the *trains* version you are using (i.e. the *trains* python package)?
Also what happens if you press ctrl-c in the middle of the execution, will it mark it as aborted?

p.s.
The server will automatically mark the experiment as aborted if there are no reports in within a 2 hour period (I think it's 2 hours, anyhow it is configurable), point being, by now, you'll probably see it as aborted :)

**Comment by databill86** [comment]
I'm using : 
```
trains==0.14.3
Python 3.7.7
Spyder 4.1.3 
```
When I pressed ctrl-c in the middle of the execution, the experiment was successfully marked as "aborted". 

Althoughj, surprisingly when I ran the simple script from the command line, it ended ! The same which continue to run when launched from Spyder. 
The script : 
```
from trains import Task
task = Task.init(project_name="TEST", task_name="test trains 2")
print("success ! ")

```

**Comment by bmartinn** [comment]
Hi @databill86 
Okay I see now, this is kind of a feature of Spyder :)
When you press the "play" button in Spyder, it will open a new ipython and execute your code there,
but it does not close the ipython session (similarly to jupyter notebook)
From *trains* perspective the process is still running, hence not marked as completed.
If you do something in the opened ipython window, it will be logged as well.

Only when you close the console window (or Spyder itself), *trains* will automatically mark the experiment as completed :)

**Comment by databill86** [comment]
I've just tested it and confirm it. When I closed the ipython window the experiment has been marked "completed". 

Thank you.
