### ISSUE TITLE
Task.enqueue raises TypeError with default parameters

### ISSUE THREAD

**Issue by H4dr1en** [allegroai/trains#138]
With `trains==0.15.0rc0`

When calling `Task.enqueue(task)`, user gets the following error:

```  
File "piping.py", line 47, in main
    Task.enqueue(task)
  File "/Users/h4dr1en/miniconda3/envs/training-py36/lib/python3.6/site-packages/trains/task.py", line 710, in enqueue
    req = queues.GetAllRequest(name=exact_match_regex(queue_name), only_fields=["id"])
  File "/Users/h4dr1en/miniconda3/envs/training-py36/lib/python3.6/site-packages/trains/backend_interface/util.py", line 125, in exact_match_regex
    return '^%s$' % re.escape(name)
  File "/Users/h4dr1en/miniconda3/envs/training-py36/lib/python3.6/re.py", line 267, in escape
    for c in pattern:
TypeError: 'NoneType' object is not iterable
```

This is because both `queue_name` and `queue_id` were not specified when calling `Task.enqueue(task)`. Nevertheless:
- The error is not straightfoward (should raise `ValueError("No queue_id/queue_name specified")`)
- `Task.enqueue` should not have `queue=None`(User should not expect a function to fail because of default values). Either:
    1. Set default value of `queue_name` to "default" (which would make a lot of sense). `queue_id` should only be considered if it is not `None` and should take the predecence over `queue_name`.
    2. Change signature: `Task.enqueue(task, queue)`, where `queue` is either an id or an name. The detection of whether `queue` is a name or an id can be done under the hood.

**Comment by bmartinn** [comment]
Hi @H4dr1en , you are correct, bug is verified.
Regrading the suggestion, the previous behavior , if both `queue_name` & `queue_id` are None, it will  select the first queue, and print a warning if there are multiple queues defined in the system.

We can:
 - preserve the current behavior
 - force either name or id 
 - use "default" queue name if nothing is provided (and probably print a warning saying we selected queue name "default". The thing is, you can always rename a queue, so we cannot count on "default" queue to always exist.

I tend towards the second option, I think it makes more sense for the user to know what they are looking for...

What do you think?

**Comment by H4dr1en** [comment]
Force either name or id is OK as long as the error message is clear I would say, otherwise change the signature to `enqueue(task, queue_name="default", queue_id=None)`.
Btw, any reason to have this function as `classmethod` and not just method?
It sounds more natural to do

```
my_task = Task()
my_task.enqueue()
```
But I can also live with the current implementation 👍

**Comment by bmartinn** [comment]
Thanks @H4dr1en , I think that this is what we will do.

Regrading `my_task.enqueue()` , the problem is you can only enqueue a Task that is not running. The initial thought behind putting it as a class service was that we wanted to convey that you cannot just enqueue your running Task i.e. yourself. 

Following a few discussions we had here #128 , we could actually add :
```python
Task.enqueue(self, allow_cloning=True)
```
Which will do what you suggested, and in case the Task is not in "draft" mode, it will just clone it and enqueue the cloned Task. I think this will definitely make it easier to use, and will actually be quite consistent with the ideas that were suggested in #128 , What do you think?

**Comment by H4dr1en** [comment]
> Regrading my_task.enqueue() , the problem is you can only enqueue a Task that is not running. The initial thought behind putting it as a class service was that we wanted to convey that you cannot just enqueue your running Task i.e. yourself.

This definitely makes sense. After giving a second thought, I like it!

>     Task.enqueue(self, allow_cloning=True)

This would clone the task, send the clone to the queue and continue or break the current script? And when the agent will execute this experimentand this line in particular, will it also clone again the task or understand and skip this instruction? I am not sure it is "worth" creating a cloned task to run the same code remotely, right?

**Comment by bmartinn** [comment]
> This would clone the task, send the clone to the queue and continue or break the current script? And when the agent will execute this experimentand this line in particular, will it also clone again the task or understand and skip this instruction? I am not sure it is "worth" creating a cloned task to run the same code remotely, right?

So I was thinking `task.enqueue` will continue execution, as task is a general object, and you might have done `Task.get_task('1123').enqueue()`, 
But it seems that what you have in mind is a code sending itself for execution.
Assuming this is the case, we either combine it with the context idea, per #128 suggestion, this will solve endless tasks creating one another (as you pointed out).

Now that I think about it, maybe we should combine the two, because what we have here is essentially a context call and with empty execution block, maybe:
```python
with m_task.enqueue(queue='default', exit=True):
    # run some code locally
    # enqueue ourselves and leave the process
```
which also supports `allow_cloning=False` which implies, if we are enqueuing ourselves then `Exit ` must be True:
```python
m_task.enqueue(queue='default', allow_cloning=False, exit=True):
```

**Comment by bmartinn** [comment]
Hi @H4dr1en 
Good news v0.15 is out with this feature [added](https://github.com/allegroai/trains/blob/master/trains/task.py#L2409)
```python
task.execute_remotely(self, queue_name=None, clone=False, exit_process=True)
```

Notice that Python cannot actually skip an execution block (i.e. with-block) (see discussion [here](https://stackoverflow.com/questions/12594148/skipping-execution-of-with-block)), so we decided not  go that route (well actually the hack suggested on the discussion works, but we thought it is just bad practice :)) 

We also added: 
[Task.running_locally()](https://github.com/allegroai/trains/blob/master/trains/backend_interface/task/task.py#L1116) if you need to have a conditional execution block

WDYT?

**Comment by H4dr1en** [comment]
Very cool! These two functions allow a lot of flexibility I think 👍 

Regarding this issue: as of 0.15.0, 
```
Task.enqueue(task)
```
will raise :
```
Exception: At least one of (queue_name, queue_id) is required
```
Which makes definitely sense! Closing here 👍
