### ISSUE TITLE
multiple calls to matplotlib fig.savefig() produce `UserWarning:  axes embedded in axes: something is wrong`

### ISSUE THREAD

**Issue by motikadosh** [allegroai/trains#139]
Hi,

Each epoch, I am visualizing several images in a figure using matplotlib subplots.
Then I use fig.savefig() to save them to disk.

The first call to fig.savefig() passes cleanly.
Each following call, even after exiting the visualize function, on next epoch for example, produces these two warnings-

```
/usr/local/lib/python3.6/dist-packages/plotly/matplotlylib/mplexporter/renderers/base.py:42: UserWarning:

figure embedded in figure: something is wrong

/usr/local/lib/python3.6/dist-packages/plotly/matplotlylib/mplexporter/renderers/base.py:54: UserWarning:

axes embedded in axes: something is wrong
```

This happens only when tracking the experiment.
How can I solve this?

Thanks,
Moti

**Comment by bmartinn** [comment]
Hi @motikadosh ,
This looks like the internal plotly warnings (basically saying, we did our best but you would probably end up with plot image, and not an interactive one). 
Anyhow, I think we disabled those warnings (because as you mentioned, they are quite annoying).
Which version of *trains* are you using?
Could you test with the latest RC?
```bash
pip install trains==0.15.0rc0
```

**Comment by motikadosh** [comment]
Hi,
I am using  trains==0.14.3,
Upgrading to trains==0.15.0rc0, seems to solve the issue!
Thanks a lot.
