### ISSUE TITLE
Could not detect iteration reporting

### ISSUE THREAD

**Issue by chloe-wang** [allegroai/trains#204]
hi,

we found that if we have some uncommitted changes in the code and the code is loading data from the hard disk which may cost 10 minutes, trains throws out below information:

Could not detect iteration reporting, falling back to iterations as seconds-from-start

and sometimes the whole process stucks here.

**Comment by bmartinn** [comment]
Hi @chloe-wang 

>Could not detect iteration reporting, falling back to iterations as seconds-from-start

This means that Trains could not detect and TensorBoard or any explicit reporting, since it needs x-axis for the machine statistics report, it will just use seconds. The default initial timeout for any iteration reporting is 3 minutes, that said if Trains detects reporting in the first 30minutes, it will stop using "seconds" for the machine statistics and revert back to the experiments iterations.

So in theory, if the pre-processing / data loading is 10 minutes, after it is done you should see a message like:
`TRAINS Monitor: Reporting detected reverting back to iteration based reporting`

> and sometimes the whole process stucks here.

What do you mean stuck? it should have no real effect on the main code itself...

**Comment by chloe-wang** [comment]
hi @bmartinn ,
thanks for the reply. "Stuck" means the whole process stops there, and cpu has very low loading, but the everything just stops. Not sure what happened. But if I remove the trains from the code, everything goes fine....

**Comment by bmartinn** [comment]
Hi @chloe-wang 
My apologies for the delay, I somehow missed a few replies :(
Could you elaborate on "the code is loading data from the hard disk " ?
Is this somehow related to #207 ?

**Comment by chloe-wang** [comment]
@bmartinn I think it's a about the version conflict of other packages. I will close the issue. Thanks.
