### ISSUE TITLE
Preserve python built-in data types when retrieving hyper parameters

### ISSUE THREAD

**Issue by n-Guard** [allegroai/trains#260]
Is it possible to preserve python built-in objects like `int, float, bool, str, list, tuple, set` when retrieving hyper parameters by calling `task.get_parameters()`?
Right now, every parameter is returned as a string and possibly needs to be converted in order to use it.
One workaround would be to call `eval()` on every parameter which I'd rather avoid due to the possibility of unintended behavior.

**Comment by bmartinn** [comment]
Hi @n-Guard 
Actually `trains` does that when you call `task.connect(some_dict_here)` , the arguments are cast back to the original type based on the `some_dict_here` values. For [example](https://github.com/allegroai/trains/blob/master/examples/reporting/hyper_parameters.py):

``` python
parameters = {
    'list': [1, 2, 3],
    'dict': {'a': 1, 'b': 2},
    'tuple': (1, 2, 3),
    'int': 3,
    'float': 2.2,
    'string': 'my string',
}
task.connect_configuration(parameters, name='test')
```
Notice the `tuple` and `list` are cast back to their types according to the **original** values in the dict.
This is although the values have to be serialized to string for storage by the backend (just like with json serialization).
The `task.get_parameters()` is kind of "under-the-hood" call , allowing you access the actual data stored, without typing getting in the way :)
Make sense?

**Comment by n-Guard** [comment]
Hi @bmartinn,

thanks for your detailed explanation!
Consider the following short script:

```
from trains import Task
task = Task.init(project_name='examples', task_name='Parameter retrieval')
task.connect({'parameter': 5})
param = task.get_parameter('General/parameter')
print(type(param))
```

When I execute this the output is `str` instead of `int`, can you confirm this? I'm using `trains==0.16.3`

**Comment by bmartinn** [comment]
Hi @n-Guard ,
I think I need to expand on how it actually works.

When you call the following in manual mode (i.e. running your own code)
``` python
my_params = {'parameter': 5}
task.connect(my_params)
```
`trains` will register the dictionary content in `trains-server`, i.e. the UI.
When you run the **same code** using the `trains-agent` the same function call `task.connect(...)` does the opposite, and instead of sending the data to the server, it will fetch the parameters form the server, cast them according to the types in the `my_param` dict and updated **in-place** the `my_params` dict.

All that to say, you do not need to call `task.get_parameter`, `task.connect` does that for you :)
Make sense ?

**Comment by n-Guard** [comment]
Ah thanks for clearing that up!

But my use case is a little bit different. What I actually want is querying parameters from a finished task.
When I execute this code:

```
task = Task.get_task(task_id=<TASK-ID>)
my_param_dict = task.connect(dict())
```

I get the following Error: "ValueError: Task object can only be updated if created or in_progress"
So the question would be: How can I get the right data type from a task that is already finished/completed?

**Comment by bmartinn** [comment]
I see now...
1. The error you are getting is because from `trains` perspective you are running in "manual mode" i.e. you want to store parameters into the Task but it is already completed, hence the error.
2. Unfortunately you have no information on the original types of the parameters (as they are deduced from the default 
dictionary), the bottom line, you can only access the "raw" data in its string format :(
3. If you wonder how you can parse the string, I think this would do the trick:
``` python
import yaml
cast_param = yaml.load(task.get_parameter('General/parameter'), Loader=yaml.SafeLoader)
``

**Comment by n-Guard** [comment]
Ok thanks for the suggestion!
I guess this workaround will suffice for now.

**Comment by dnhkng** [comment]
I have a use-case where I need to access the parameter types with the original type:

I use Argparse to define my model and do things like choosing how often I log data based on iteration number. 

If I want to load a previous experiment, I can use:
`previous_task = Task.get_task(task_id=<TASK-ID>)`

and continue an experiment with:
`task = Task.init('examples', 'continue-run example', continue_last_task=TASK-ID>)`

But I need the parameters I would have gotten from Argparse to rebuild the model! If I use:
`previous_task.get_parameter()`
I just get strings.

What is the correct way to continue experiments with the old parameters?
i.e. Move the previous_task parameters to an Argparse args.__dict__?
