### ISSUE TITLE
When debugging in Vscode, exiting the debugger leaves an experiment hanging in the UI

### ISSUE THREAD

**Issue by mhashas** [allegroai/trains#261]
Pressing the red square while debugging results in a hanging experiment. This can get quite annoying if you are doing a lot of these debugging experiments as you have to spend a minute aborting all experiments

Expected:
After pressing the red square, the experiment gets status Aborted, anything else other than Running :) 

![Screenshot 2020-12-04 at 14 58 36](https://user-images.githubusercontent.com/13119609/101172361-60382b00-3641-11eb-9bcf-739a7419ad16.png)
<img width="110" alt="Screenshot 2020-12-04 at 14 58 46" src="https://user-images.githubusercontent.com/13119609/101172368-6201ee80-3641-11eb-9aaf-b650a49e069a.png">

**Comment by bmartinn** [comment]
Hi @mhashas ,
> Pressing the red square while debugging results in a hanging experiment. 

This sounds like a bug in the atexit callback, this is when `trains` sets the Task to "aborted" and flush all the events just before the process ends.
I'm assuming that after a while you just kill the process, obviously before the Task is set to aborted.

Can you share a code snippet to reproduce the issue ?
What is the exact setup (OS, Python, VSCode, Trains version etc.) ?

**Comment by mhashas** [comment]
Hi,

OS: macOS 11.0.1
Python: Python 3.8.5
VsCode:  1.51.1
Trains: 0.16.3

So the task keeps on Running forever (i have never timed it but its definitely more than 30 minutes). I have to manually abort it from the UI.

**Comment by bmartinn** [comment]
Hi @mhashas 

Two different issues here:
1. When pressing the "stop" icon in VSCode, instead of sending SIGTERM it sends SIGKILL and immediatly kills the process. This means `trains` has no opportunity to mark the Task as aborted (in comparison, pycharm sends SIGTERM and then `trains` can catch it and set the Task as aborted, before actually leaving the process).
This is a known issue with VSCode, it seems they solved it for NodeJS but not for Python:
https://github.com/microsoft/vscode-node-debug2/issues/101
2. Are you saying that when your process ends, while running with the debugger, over SSH, the process hangs instead of leaving ? Does that happen with any code? Could you test with one of the toy examples ([scalars example](https://github.com/allegroai/trains/blob/master/examples/reporting/scalar_reporting.py)) ?

**Comment by mhashas** [comment]
Hi,

I think 1) encompasses the issue. Everything is ok with the process, is just the trains UI that is not updated and shows the task as 'Running' instead of 'Aborted', which is not so nice, especially if you want to keep track of experiments that are actually running.  In order to manually solve it, I have to mark the processes as Aborted from the UI. 

I did try the scalars example, when pressing the stop icon from vscode the experiment is still showing as running in the UI :)

**Comment by bmartinn** [comment]
> I did try the scalars example, when pressing the stop icon from vscode the experiment is still showing as running in the UI :)

Yes, but if you do not press the "Stop" , and let it finish, will it just hang, or exit properly and set the task as completed ?

**Comment by mhashas** [comment]
Exit properly and set the task as completed, this is what happens with my experiment as well, the only issue is when pressing the stop button

**Comment by bmartinn** [comment]
Thanks @mhashas .
If that is the case, it seems there is very little we can do, this is a VSCode bug/feature-request :(

That said, you can lower your [activity watchdog](https://allegro.ai/docs/deploying_trains/trains_server_config/#non-responsive-task-watchdog) threshold so the watchdog will set the task to aborted after X seconds of inactivity (the default value is 2 hours).

**Comment by mhashas** [comment]
Thanks :)

**Comment by mhashas** [comment]
Hi @bmartinn,

There seems to be no services.conf file in the path mentioned. Should we create one?

**Comment by bmartinn** [comment]
@mhashas yes please do, you can copy-paste the content from documentation :)
