### ISSUE TITLE
Bug with automatic upload of matplotlib plots

### ISSUE THREAD

**Issue by Danzip-r** [allegroai/trains#34]
plt.imshow(image)
plt.title("title")

This works and uploads the image automatically to the debug_images

plt.title("title")
plt.imshow(image)

This doesn't upload the image automatically.

**Comment by bmartinn** [comment]
@Danzip-r, I can't seem to reproduce this behavior.
 This code works as expected:

```
import matplotlib.pyplot as plt
import numpy as np
from trains import Task

task = Task.init(project_name='examples', task_name='Matplotlib imshow example')
m = np.eye(256, 256, dtype=np.uint8)
plt.title('test')
plt.imshow(m)
plt.show()
print('done')
```

What are the exact versions of python/trains/OS you are using?

**Comment by Danzip-r** [comment]
python 3.5 trains 0.10.3rc4 ubuntu 16.04 It seems that actually plt.show() is what affects this behaviour as in with plt.show() I can see the image and without I can't

[bug.txt](https://github.com/allegroai/trains/files/3456486/bug.txt)

**Comment by bmartinn** [comment]
Hi @Danzip-r 
I Tested the attached code, on Ubuntu 16.04, Python 3.5.2, Matplotlib 3.0.3, trains 0.10.3 (final),
working as expected. 
Please notice that you have to call plt.show() in order to present the image ([ref](https://stackoverflow.com/questions/42812230/why-plt-imshow-doesnt-display-the-image?rq=1)), without calling it, matplotlib will not actually generate a figure (regardless of the matplotlib backend you are using, Agg, QT, PyCharm, etc.)

Both
```
...
plt.title("prediction:{} label :{}".format(predicted[a[0]], y_test[a[0]]))
plt.imshow(X_test[a[0]].reshape([28, 28]))
plt.show()

```
and
```
...
plt.imshow(X_test[a[0]].reshape([28, 28]))
plt.title("prediction:{} label :{}".format(predicted[a[0]], y_test[a[0]]))
plt.show()
```

Will upload the image to the "Debug Images" section.

Could you verify again the problem exists with v0.10.3 (I believe it was fixed in the final release)

**Comment by Danzip-r** [comment]
Yup you have to call plt.show() this was our main issue
