### ISSUE TITLE
Using trains on a batch-job system

### ISSUE THREAD

**Issue by moskomule** [allegroai/trains#37]
Hi, I appreciate `trains,` which helps my research projects.

Now I want to use `trains` on a batch-job system consisting of a login node and several GPU nodes. I created a `trains.conf` on the login node and pushed a job with `trains` on a GPU node. Then I got the following error.

```
Retrying (Retry(total=239, connect=239, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x2aaf57a2cc50>, 'Connection to XXX.XXX.XXX.XXX timed out. (connect timeout=3.0)')': /auth.login
```

I checked `XXX.XXX.XXX.XXX` is reachable from the GPU node I ran the job.

Also, I follow the answer in https://github.com/allegroai/trains/issues/7 and modified a line of `trains.conf` to 

```
api { verify_certificate = False } 
```

But I got the same message.

It would be helpful if you have any advice. Thank you for your advance.

**Comment by bmartinn** [comment]
Hi @moskomule , from the 'timeout' error, it looks like the problem is not a certificate issue. 
I **highly** recommend reverting #7 addition to the configuration file (this solution is only for very specific enterprise setups where https requests are being intercepted on purpose).

With regards to the GPU node connection erros, please verify that can reach the actual server at XXX.XXX.XXX.XXX.
That means not only ping-ing it but checking you can reach the api-server port.

You can very quickly verify with:

`$ curl http://XXX.XXX.XXX.XXX:8008`

(this assume you have the trains-server running on XXX.XXX.XXX.XXX with the default api-server port configuration: 8008)

If the `curl` command fails, or just hangs, it means the trains-server is not accessble from the GPU Node, and hence the connection issues you are getting.

My guess is that due to some firewall/routing/NAT issues, the trains-server is not accessible from the GPU cluster.

**Comment by moskomule** [comment]
Hi @bmartinn, thank you for your reply.

Yes, your indication was correct and the train-server was not accessible from the GPU cluster.
