### ISSUE TITLE
Comparing experiments with time axis instead of iterations

### ISSUE THREAD

**Issue by motikadosh** [allegroai/trains#55]
I would like to compare experiments with X axis as time instead of iteration.
This can have two approaches and uses-
With t=0 for all experiments- would enable to show for similar experiments which is faster.
With t as actual time+date- would show experiments had some issue in a certain time in the day, for example due to network overflow, or some HW failure.

If it is already possible and I missed it, I apologize :-)

![image](https://user-images.githubusercontent.com/26479032/68861446-3fc6c700-06f4-11ea-8ead-e46dde1eb45d.png)

Thanks a lot!

**Comment by bmartinn** [comment]
Hi @motikadosh in the experiments page (and the results page), there is a cog wheel icon, press on it and you will be able to select  graph-smoothing, and Wall-Time/Iterations.

Unfortunately, it seems there is a bug and in the comparison page, the cog wheel does nothing...
This bug fix will be part of the next *trains-server* release, due to be released in a couple of weeks.

I'll update here once we have a fix available.

**Comment by motikadosh** [comment]
Cool! Thanks!
Yes, the cogwheel does nothing at the moment, tried it...

**Comment by bmartinn** [comment]
Hey @motikadosh,  I forgot to update here...
*trains-server* v0.12.1 is out, and the bug is fixed :tada:

**Comment by bmartinn** [comment]
Hi @motikadosh ,
It seems there was still some minor issue left, now fixed in the new release of Trains-Server v0.13.0
