### ISSUE TITLE
Using Trains and PyTorch multiprocessing launch tool

### ISSUE THREAD

**Issue by igolan89** [allegroai/trains#59]
Hi,
Is there any way to use Trains with PyTorch's multiprocess launch tool?
The task is created multiple times and I want it to be created only in the main process

**Comment by bmartinn** [comment]
Hi @igolan89 , I'm assuming you are referring to [torch.distributed.launch](https://github.com/pytorch/pytorch/blob/master/torch/distributed/launch.py)

I'm assuming you are running with NCCL support with multiple processes on the same machine. 
In that case, instead of initializing the task on all nodes you should only initialize on the main node (LOCAL_RANK==0). Stdout is piped to the main node anyhow, and since you are storing the models on the main node only, the model logging auto-magic will work out of the box.

Try running your code with:

```
if int(os.environ.get('LOCAL_RANK', 0)) == 0:
    task = Task.init(project_name='distributed', task_name='torch.distributed.launch test example')

```
Please update here if it worked :)

**Comment by igolan89** [comment]
Workes like a charm! Thanks!
