### ISSUE TITLE
Prior artifacts getting deleted when I try to register_artifact from another process

### ISSUE THREAD

**Issue by RomAviad** [allegroai/trains#63]
Steps to reproduce:

1.  Create a task and upload an artifact (either by `Task.upload_artifact` or by `Task.register_artifact`)
2. Load the task in another process using `Task.get_task` by the task ID from step 1
3. Upload another artifact using `register_artifact`

As a result, the artifact uploaded in step 1 would not appear under task artifacts, and only the artifact from step 3 would appear

**Comment by bmartinn** [comment]
Hi @RomAviad 

`Task.upload_artifacts` supports artifact overwriting, it allows us to support constant update of artifact, for example while running a long experiment (for example, maybe additional data you would like to have with your checkpoints).

One thing that I'm missing from the scenario you described, is step 3 intentionally uploading an artifact to the Task it received in step 2?
Won't it make sense for the code to to upload the artifact to its own Task?

Could you please elaborate on the specific use case you have, and how the artifacts are used in the Task pipeline?

**Comment by RomAviad** [comment]
Hey @bmartinn 

My use case is a map-reduce-like inference pipeline.
I have a producer that creates a task, uploads the input df as an artifact, and dispatches data points to a queue (along w/ task ID); Consumers consume that queue, process data points with a model, and produce results to a results queue (task ID is propagated to that queue); A reducer consumes the results queue, loads the task, and uploads result batch data frames as registered artifacts (I have quite large runs, so I shard the results instead of uploading a huge data frame).

**Comment by bmartinn** [comment]
Please correct me if I misunderstand, from your description it looks like there is a **single** task, where that task goes through several different processing steps:

0) Task creation
1) Upload Data (pandas DataFrame) to the task using the artifacts mechanism
2) Data Processing, where the input DataFrame is processed (in parts, say we have 4 consumers, meaning we divide the data 4 ways, each consumer will process its share independently from the rest)
3) Consumers upload their result (here I'm unsure on the mechanism, so I'll assume artifacts as well)
4) Reducer will take all consumer results (4 in the example above) and create one combined result, again stored as an artifact.

If this is the case, I would expect to get the following artifacts on the Task:

```
{
  'input_df': # step 1
  'processed_shard_1': # step 2 - consumer 1
  'processed_shard_2': # step 2 - consumer 2
  'processed_shard_3': # step 2 - consumer 3
  'processed_shard_4': # step 2 - consumer 4
  'output_processed_data': # step 4
}
```

Is this what you had in mind?

I would like to suggest another approach to the problem:

I sounds like it would make sense to have a few tasks instead of one reused by multiple processes.
For example:
Task 0 : Holds the input DataFrame
Tasks 1-5 : Get as hyper-parameter `Task 0` ID  and store their output in their own artifact section
Task 6 : Gets as hyper-parameter `Task 1` through `Task 5` IDs and stores the combined result in its own artifact section

This way you can use *trains-agent* to manage the execution, you will have full visibility into the processing of each step, and the code is very explicit, you have input artifact from previously processed task and you store the output on your own task.

I think it makes a simple and transparent data processing flow, what do you think ?

**Comment by RomAviad** [comment]
Your suggestion makes some sense to me, but I'm not sure it would be convenient to track at my work scale. In typical use (with fairly large shards of 100K-200K rows each) I'm expecting about 200 shards per processing batch (think of it as an experiment, so it has to be grouped with other experiments of the same project)

The following (partial) code is kind of what I have in mind (and in practice)

```python
# producer functionality
def producer_functionality(input_df):
  task = Task.init(...)
  task.upload_artifact(name="input_df", artifact_object=input_df)
  for idx, row in input_df.iterrows():
    row_dict = row.to_dict()
    row_dict["task_id"] = task.id
    model_queue.push(row_dict) # this can be SQS/Rabbit/Kafka/whatever other broker you can imagine 

######
# consumer logic; happens in multiple distributed workers
def consumer_functionality():
  msg = model_queue.get_message()
  result = magical_stuff(msg) 
  # result would be a dictionary and would propagate the task id that was created in the producer
  results_queue.push(results) # separate queue

######
# reducer logic; aggregate consumers results into artifacts 
def reducer_functionality():
  msgs = results_queue.get_message_bulk(size=100) # assume we get a list of dictionaries
  task = Task.get_task(task_id=msgs[0]["task_id"])

  current_df = get_current_df() 
  # reducer is somewhat stateful and get_current_df would get the last registered artifact from the task that conforms with "results_<shard_number>" if it doesn't exceed shard size, otherwise None
  if current_df:
    for msg in msgs:
      current_df.iloc[len(current_df)] = msg
  else:
    current_df = pd.DataFrame(msgs)
    df_name = get_df_name() # "results_0001" for example
    task.register_artifact(df_name, current_df)
    set_current_df(current_df) # set the state
```

**Comment by bmartinn** [comment]
I agreed, if you are expecting 200 shards, it is definitely not practical to have them as different experiments.

The code sample seems like a great way to get it this pipeline working!

Two things to notice:

1) In the code sample you are using `task.register_artifact`, this will keep `current_df` in memory and will continue to monitor its changes and upload it. If you know in advance that the `current_df` object will not change, you should use `task.upload_artifact` that will upload and register the artifact, but will not continue to monitor the dataframe or hold it in memory.

2) The task.artifacts is not atomic, meaning if you have two machines adding two different artifacts to the same task (notice machines, if these are different threads/processes there is no problem) they might overwrite one another artifacts section (It will be fixed in the next *trains-server* version)

**Comment by RomAviad** [comment]
The code sample seemed to be a good way to me too, but then I faced the issue I described here in the first place - `producer_functionality` uploads the input data frame artifact and I can see it under the task artifacts, but only until the first time `reducer_functionality` registers an artifact to the task for the first time :(

**Comment by bmartinn** [comment]
I understand, and I think we now have a handle on the issue.
I'll update here once we have an RC released, should not take long :)

**Comment by RomAviad** [comment]
Thanks @bmartinn! Works as expected with [0.12.2](https://github.com/allegroai/trains/tree/0.12.2)

**Comment by bmartinn** [comment]
Great to hear!
