### ISSUE TITLE
model snapshots are not written either locally or to s3

### ISSUE THREAD

**Issue by boazpe** [allegroai/trains#72]
Hi,
Following your FAQ, i've added the output_uri to Task.init().
When i pass a local path, a folder is created on that path on the client machine (shouldn't it be created on the trains-server machine and files get uploaded there?) but no sub-folders or model files are written during the train process.

When iv'e tried giving an s3 bucket no folder is written to it.

my client os is ubuntu.
I'm using tensorflow 1.14.0 with tensorflow.keras.callbacks.ModelCheckpoint callback for model snapshots.
the trains client version i'm using is trains 0.12.2, and for trains server I've deployed the ami-04293fbba6d3acad1 (eu-west).

**Comment by JDennisJ** [comment]
Hi @boazpe 

Do you see the `output_uri` you provided in the task's execution part (under `OUTPUT -> DESTINATION`)?

Do you see the model in the `artifacts` section? If so, clicking the `Output Model` should send you to the models section, does it have your output_uri in the MODEL URL?

BTW, if you want every task to use the same output_uri, you can update your trains.conf file to use a specific one. Under `sdk.development` change the `default_output_uri` to `<your_selected_output_uri>`.

**Comment by JDennisJ** [comment]
Hey @boazpe 

A few notes on how/when `output_uri` is used.

When your code stores a model/checkpoint using pytorch/tesorflow/keras/scikit-learn(joblib) , if `output_uri` exists, Trains will create a subdirectory under `output_uri` and copy the model into it. The folder structure is `<output_uri>/<project_name>/<experiment name>.<experiment id>/models/...`

If you are uploading an artifacts using `task.upload_artifact(...)` , and `output_uri` exists, then instead of the artifact being uploaded to the *trains-server* it will be uploaded to `output_uri` with similar folder structure `<output_uri>/<project_name>/<experiment name>.<experiment id>/artifacts/...`

The idea is that instead of directly storing large artifacts/models on the *trains-server*, it makes sense to store them on object-store/shared-folder optimizing for cost & performance.

Notice that you can also quickly get the artifacts from other tasks, thus creating a proper data processing pipeline.

**Comment by boazpe** [comment]
Hi,
Thanks again for your quick reply and sorry for my late reply.
I noticed than on epoch end I get "trains - WARNING - can't pickle _thread.RLock objects", Does this warning give you any clues?
I tried to search for this  comment in trains repository but didn't find it..
and Keras does manage to save the model snapshot to disk.

I Also tried to train a different model and than everything works OK (i have a pipeline where I use to train different models so it should be the same code just different keras models).
I'll try to find out what difference between the models causes this issue. 

BTW, i'm not using task.upload_artifact(...) , just setting the output_uri in task.init() as i saw in trains usage examples.

**Comment by boazpe** [comment]
Found out what's causing this issue.
In my keras model i have a Lambda layer that crops one tensor by the shape of another tensor. 
I've used Lambda layer 'arguments' filed to pass the Tensor which I crop by, Turns out this causes the issue. When i call the layer on the two tensors together, the model is uploaded and all is good.
To clarify:
this causes the issue: 
`skip_cropped = Lambda(crop,name="crop",arguments={'crop_by':u})(skip)`
this is OK:
`skip_cropped = Lambda(crop,name="crop")(skip,u)`

google does return results for 'TypeError: can't pickle _thread.lock objects'  but these are far beyond my level of understanding.

hopefully this change won't cause issues with my code (since this creates a different tensorflow computational graph and i'm running code that relies on traversing the graph)

**Comment by bmartinn** [comment]
Hi @boazpe 
We also encountered the "_thread.RLock objects" error, there is already a fix, it might be related to a different usage scenario, but worth a try:
`$ pip install trains==0.12.3rc0`

> BTW, i'm not using task.upload_artifact(...) , just setting the output_uri in task.init() as i saw in trains usage examples.

Yes, this is the correct choice :)


Regrading the lambada (anonymous) function causing issues with pickle, I think that what happens is *trains* catches the exception, and instead of passing it on, just prints a warning. 

Do you have a short sample code to reproduces it?

**Comment by boazpe** [comment]
Hi,
Sorry again for the late reply.
Below is the shortest code that i can come up with. 
setting CAUSE_UPLOAD_ISSUE = True should cause the  "_thread.RLock objects"  warning and the model won't get upload (However the model will be trained).

`from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input,Conv2D,Concatenate,Lambda,MaxPool2D,Flatten,Dense
import tensorflow as tf
import numpy as np

tf.executing_eagerly()
tf.enable_eager_execution()

def crop_by_input(inp):
    to_be_cropped=inp[0]
    crop_by=inp[1]

    sh=to_be_cropped.get_shape().as_list()
    out_shape=crop_by.get_shape().as_list()
    margin_r=  int((sh[1]-out_shape[1])/2)
    margin_c= int((sh[2]-out_shape[2])/2)

    cropped=to_be_cropped[:,margin_r:sh[1]-margin_r,margin_c:sh[2]-margin_c,:]

    return cropped

def crop_by_arg(inp,crop_by):
    to_be_cropped=inp


    sh=to_be_cropped.get_shape().as_list()
    out_shape=crop_by.get_shape().as_list()
    margin_r=  int((sh[1]-out_shape[1])/2)
    margin_c= int((sh[2]-out_shape[2])/2)

    cropped=to_be_cropped[:,margin_r:sh[1]-margin_r,margin_c:sh[2]-margin_c,:]

    return cropped

from trains import Task

task = Task.init(project_name='issues', task_name='Lambda',output_uri="s3://beewise-cv-dev/trains")

CAUSE_UPLOAD_ISSUE=True

inp=Input(shape=(32,32,1))

h1=Conv2D(kernel_size=(3,3),filters=16,activation='relu')(inp)

x=MaxPool2D(pool_size=(2,2))(inp)
h2=Conv2D(kernel_size=(3,3),filters=16,activation='relu')(x)

if CAUSE_UPLOAD_ISSUE:
    h1_cropped = Lambda(crop_by_arg, arguments={'crop_by': h2})(h1)
else:
    h1_cropped = Lambda(crop_by_input)([h1,h2])


h3=Concatenate()([h1_cropped,h2])

h3=Flatten()(h3)
out=Dense(units=1,activation='sigmoid')(h3)


m=Model(inputs=[inp],outputs=[out])


m.compile(loss='binary_crossentropy',optimizer='sgd')

X=np.random.rand(1000,32,32,1)
Y=np.random.rand(1000,)
from tensorflow.keras.callbacks import ModelCheckpoint
m.fit(X,Y,epochs=100,callbacks=[ModelCheckpoint('/tmp/Lambda_issue.h5', save_weights_only=True)])`

**Comment by bmartinn** [comment]
@boazpe thanks! that really helps.
With to your example code, the problem was located quickly.
You can expect an RC with a fix soon :)

**Comment by boazpe** [comment]
Glad I could help and repay you a bit

**Comment by bmartinn** [comment]
@boazpe, as promised RC with a fix:

`$ pip install trains==0.13.1rc0`

**Comment by bmartinn** [comment]
Hi @boazpe ,
We've just released Trains v0.13.1 which includes this fix :)
`$ pip install trains==0.13.1`

**Comment by boazpe** [comment]
Great, thanks!
