### ISSUE TITLE
Deleting project/experiment

### ISSUE THREAD

**Issue by elinep** [allegroai/trains#84]
Hi, 

My team uses trains systematically even when prototyping. Thus we have a lot of non-relevant data (images, models) that we would like to delete from time to time.
Typically we use a naming convention such as "__temp_project" when developing. We also manually archive bad runs.
We would like to be able to delete these runs to save disk space and keep the board clean. 
The project's delete action seems to only remove entries in the database and leaves raw data intact.

Is it possible to do it properly without fiddling with a terminal on the server?

**Comment by bmartinn** [comment]
Hi @elinep , I'm glad to hear you guys are using *trains* constantly :)

My guess is that you are looking to delete old files from the *trains-fileserver* storage (feel free to correct my assumption if I miss understood)

Since the storage itself is detached from the *trains-server*, and can be easily mapped to any cloud object-storage or shared-folder, my assumption that somewhere there is a folder where all models/debug-images reside. 
If you are running the default setup, this folder will be `/opt/trains/data/fileserver/` (managed by the *trains-fileserver* as a simple file upload service)

If that is the case, this short script below will iterate over the folders (every folder matches a project name), then it will get all the experiments under that project, if it fails, it means the project was deleted and we can remove the entire folder. If the project exists, we go over all the experiments checking which one is archived, then we delete its sub-folder.

This script can be executed daily as a cron job on the server, that said, **please** **please** **please** check it before you execute it, there might be a bug here, and this is a destructive operation!

Enjoy :smile: and :crossed_fingers: 

``` python
import os
from shutil import rmtree
from glob import glob
from trains import Task


base_fileserver_folder = os.path.abspath('/opt/trains/data/fileserver/')
for project_folder in glob(os.path.join(base_fileserver_folder, '*')):
    try:
        tasks = Task.get_tasks(project_name=project_folder)
    except ValueError:
        tasks = []

    if not tasks:
        # There is no such project in the system, remove the project folder
        rmtree(project_folder)
        continue

    # now iterate over the tasks deleting archived experiments
    for task in tasks:
        if 'archived' in task.data.system_tags:
            # find the correct folder that matches the task.id
            task_folder = list(glob(os.path.join(project_folder, '*.'+task.id)))
            if len(task_folder) == 1:
                rmtree(task_folder[0])

    # try to delete the project folder, it will only work if it is empty.
    try:
        os.rmdir(project_folder)
    except OSError:
        pass
```

**Comment by elinep** [comment]
Thanks for the script. Indeed that should do the job.
Any chance that this kind of feature could be integrated in trains server and the web UI in the future?

**Comment by bmartinn** [comment]
My approach would probably be to have that script as an additional service running as part of the *trains-server* (specifically *trains-fileserver*) , what do you think?

**Comment by elinep** [comment]
Does it mean that this service would not be available when using, azure, aws or google storage? Doesn't it feel a bit too specific?
So far we rely on __trains-fileserver__ to hold our data (curves, models) but we plan to move to another storage solution easier to manage/administrate. It would be great if this "garbage collector" feature was independent of the storage solution.

Please note I have no idea the amount of work it implies on your side ;), I'm just throwing ideas.

**Comment by bmartinn** [comment]
Funny you mention that, #85 is about moving from storing artifacts on *trains-fileserver* to object-storage (we support S3/GS/Azure)

As mentioned there, you can basically map the bucket as a volume in the machine running the "cleanup service" and it should work out-of-the-box.

Since this script mainly list files and deletes them, performance is not an issue, and it's a a quick trick to adapt it to any object-storage.
